### PR TITLE
Create some examples #31

### PR DESCRIPTION
**Pull request by Crocmagnon**
I created a single page with some examples. See #31.

### CODE REVIEW

**Comment by Crocmagnon** [comment]
Do you have any particular requirement ?
I created a basic sample page using the classes provided in your CSS but maybe you expect something more elaborated ?

**Comment by Crocmagnon** [comment]
I added a more realistic example. Could you please give your opinion on it ?
Am I going in the right direction ? 😊

**Comment by Crocmagnon** [comment]
@ummahusla, I added another example. Don't hesitate to tell me if it suits your needs ! 😄

**Review by ummahusla — COMMENTED** [review]
I've checked your examples, they seem to be okay, but I think separating all examples into a separate repository. I will keep this PR active, so I can merge it later on.

**Comment by Crocmagnon** [comment]
FYI, Bootstrap stores their examples in the same repo 👍 

Thanks for your comment though 😊

**Comment by ummahusla** [comment]
@Crocmagnon Well, I'm I not really interested in cloning Bootstrap tho! 👍

**Comment by Crocmagnon** [comment]
Haha I understood 😄 

The idea behind my comment was more "just in case you didn't know" 😊

**Comment by ummahusla** [comment]
@Crocmagnon Hey! I've created a `/example` folder, please check it out and create a new PR if you have anything to update.

**Pull request closed without merging**
