### PR TITLE
added new LESS file

### PR DESCRIPTION
**Pull request by Adijav**

### CODE REVIEW

**Review by ummahusla — CHANGES_REQUESTED** [review]
I've noticed several formatting issues and non-consistent tab indention (please use 4 spaces for 1 tab).

**Comment by Adijav** [comment]
I have updated the changes. Please let me know if any more changes are required.

**Review by ummahusla — CHANGES_REQUESTED** [review]
Thanks for formatting it properly. 

Next thing to do is to keep LESS version consistent to SASS one. Please check [SASS version](https://github.com/PotatoCSS/PotatoCSS/blob/master/potato.scss) and make your LESS version to be similar to it. 

Thanks

**Comment by Adijav** [comment]
I don't understand what exactly you mean by consistent. Can you please explain more? some of the SASS syntax is not supported by LESS

**Comment by Blue-EyesWhiteDragon** [comment]
I suggest this be closed.

@Adijav , I suggest you work on the recently merged `potato.less` file.

**Pull request closed without merging**
