### PR TITLE
Working examples

### PR DESCRIPTION
**Pull request by anurag-ks**

### CODE REVIEW

**Comment by ummahusla** [comment]
@anurag-ks Hi, there is no need to add tons of code for no reason. I wanted to keep examples clean and simple as much as possible. So it help while copy and pasting.

**Comment by anurag-ks** [comment]
Oh okay I get your idea, but my suggestion would be to put these example
code snippets on a website/docs, that way it would serve your purpose and
keep these working examples as a reference. Users would always want to see
working stuff. And for snippets they could just refer to the docs or the
website. What do you say ?

**Comment by ummahusla** [comment]
@anurag-ks That's a good idea, but I haven't yet decided where I supposed to put. We have two ways either https://github.com/PotatoCSS/potatocss.github.io or https://github.com/ummahusla/PotatoCSS/. I will think about that over the weekend, because I wanted to make a docs and finally publish the framework.

**Comment by anurag-ks** [comment]
Put it on a place where you would expect maximum audience, so the website
would be cool.

**Comment by ummahusla** [comment]
@anurag-ks Yeah, can agree with you but even tho, I need to restructure the main repository folder and style readme, and only after that update the docs website and provide examples.

**Pull request closed without merging**
