### PR TITLE
Added feature/modal

### PR DESCRIPTION
**Pull request by bobharley**
I added a modal class, based on bootstrap 4 modal. I also included an example on the `/examples` folder.
- You can specify the toggle element/elements by adding `data-toggle="modal"` attribute.
- You can specify which modal to toggle by adding `data-target="(queryselector)"` attribute to the toggle element. The query selector can be an id `#modal-1`, a class `.modal-1`, or any selector you can put inside the `document.querySelector()` function.
- You can also specify the close toggle by adding `data-action="close"` attribute on an element inside the `.modal` container.
- The scrolling of the body will be disabled when you open a modal, and also it will add a padding based on the calculated width of the scrollbar(if there is a scrollbar) on the right to prevent the page from changing width when the scrollbar is disabled.
- The modal can also scroll independently when its content become too long.
- I also added a `large` and `small` class.
- Pressing the esc key will close a modal.

### CODE REVIEW

**Review by ummahusla — CHANGES_REQUESTED** [review]
Can you please merge latest develop here. Moreover, should I merge the gulp task first or this one?

**Comment by bobharley** [comment]
Merge the `feature/gulp` branch. And then I'll update the `feature/modal` branch

**Comment by bobharley** [comment]
Are you not gonna merge it yet?

**Comment by ummahusla** [comment]
@bobharley Good job on making this! Fancy adding your example into the docs website? You can make a new PR to this repository - https://github.com/PotatoCSS/potatocss.github.io. Let me know if you are interested in this.

**Review by ummahusla — APPROVED** [review]

**Comment by bobharley** [comment]
I'll se what I can do

**Pull request merged**
