### PR TITLE
LESS + more

### PR DESCRIPTION
**Pull request by Blue-EyesWhiteDragon**
[+] Changed Heading (h1, h2 etc..) values.
[+] Added border-box to universal (*) selector
[+] Added LESS
[~] Updated README
[~] Changed README, etc, to uppercase filenames
[~] Updated SASS to match.

### CODE REVIEW

**Review by ummahusla — COMMENTED** [review]
Great PR mate! Thank you for your contribution.

Why do you think utility files like `contributing` should be all uppercase? Is there any particular reason for that?

**Comment by Blue-EyesWhiteDragon** [comment]
C9 (the IDE I work with when on Chromebook) doesn't read "license.md" only "LICENSE.md", strange I know. To add to the previous statement, GitHub inits with the files in uppercase as far as I am aware. 3rd point: brings more attention to the file, and declares its importance in my mind.

**Review by ummahusla — CHANGES_REQUESTED** [review]
There is an issue with `.container { max-width: 960% }. 

Additionally, why you are changing the headers size?

**Comment by Blue-EyesWhiteDragon** [comment]
[SASS file](https://github.com/ummahusla/PotatoCSS/blob/master/potato.scss) @ Line 106, it has the line:

``` SCSS
max-width: 10 * $primary-width
```

I left this unchanged.

---

H1, H2, H3 elements etc..

My thoughts were:

Increasing the difference between the heading/header sizes will guarantee better readability and distinction of the content below due to the heading font-size.

**Comment by Blue-EyesWhiteDragon** [comment]
The issue with the SASS max-width has been fixed, echoed into the LESS file and now is no longer a problem in the CSS/Minimised CSS; 960% should now be 960px.

A little mix up on units by the previous SASS author, I didn't notice. I implemented the 960px as a variable in the `/* Variables */` section under the name of `$container-max-width` and `@container-max-width`

**Comment by ummahusla** [comment]
Well, I still want to get the previous header sizes if it's possible.

**Comment by Blue-EyesWhiteDragon** [comment]
Alright, will revert back now.

**Pull request merged**
